### ISSUE TITLE
iConference 2020 

### ISSUE THREAD

**Issue by nniiicc** [CouncilDataProject/Research#1]
URL - https://ischools.org/iConference-2020-Preview 

Idea: 
- Engineering a reliable search across municipal governments is difficult because of heterogeneity of data structures ... 
- This reflects a longstanding tension in Information Systems ... Yahoo (manual labeling) vs Google (algorithmic indexing) 
- The latter is now possible given access to media produced by Open Meetings laws... 
- We take this challenge up... and provide a method of indexing that preserves the contextual integrity of municipal gov data

**Comment by evamaxfield** [comment]
Closing in favor of #2
